#           __ _
#  __   __ / _| | __ _ _ __ ___
#  \ \_/ /| |_| |/ _` | `__/ _ \
#   > _ < |  _| | |_| | |  | __/
#  /_/ \_\|_| |_|\__,_|_|  \___|

# Edit plugin configurations here.

enabled: true

