#           __ _
#  __   __ / _| | __ _ _ __ ___
#  \ \_/ /| |_| |/ _` | `__/ _ \
#   > _ < |  _| | |_| | |  | __/
#  /_/ \_\|_| |_|\__,_|_|  \___|
# Simple Sidebar - by xFlarinFlint (flintintoe or Flarin)

# Edit plugin configurations here.

# Please do not change this value to avoid unexpected errors
config_version: 1.2.0

#### Plugin

# Enable this plugin
plugin_enabled: true

### Default sidebar

# If this is true, the first sidebar will be loaded when a player joins the server
set_on_login: true

### AFK sidebar

# Duration of inactivity in seconds for a player to go into AFK mode
# Set to 0 to disable AFK sidebar feature
afk_timer: 30
# Allow people to set themselves to AFK
allow_change_afk: false
# If this is true, placeholders will be updated regularly in afk sidebar
afk_placeholder_update: true

### Optimisation (for performance)

# Update sidebar only when placeholders update (May cause lag)
update_placholder_async: true

# Setting to update specific placeholders is coming soon

# Update sidebar on set intervals
update_sidebar_sync: false
# Set the delay in seconds between each automatic sidebar update
sidebar_update_timer: 1



