name: SimpleSidebar
author: xFlarinFlint
version: 0.7.4_RC2
main: com.gmail.flintintoe.SimpleSidebar

depend: []
softdepend: [Vault, WorldGuard, WorldEdit]

commands:
  sidebar:
    description: Sidebar player commands
    aliases: [sb]
    usage: /sidebar
    permission: simplesidebar
  sidebaradmin:
    description: Sidebar admin commands
    aliases: [asidebar, asb]
    usage: /adminsidebar
    permission: simplesidebaradmin

permissions:
  simplesidebar:
    description: Allows sidebar player commands
    children:
      simplesidebar.use:
        default: true
      simplesidebar.see:
        default: true

  simplesidebaradmin:
    description: Allows sidebar admin commands
    children:
      simplesidebaradmin.check:
        default: op
      simplesidebaradmin.set:
        default: op
      simplesidebaradmin.reload:
        default: op
