name: SimpleSidebar
author: xFlarinFlint
version: 0.7.0_RC1
main: com.gmail.flintintoe.SimpleSidebar

depend: []
softdepend: [Vault, WorldGaurd, WorldEdit]

commands:
  sidebar:
    description: Sidebar player commands
    aliases: [sb]
    usage: /sidebar
    permission: simplesidebar.use
  sidebaradmin:
    description: Sidebar admin commands
    aliases: [asidebar, asb]
    usage: /adminsidebar
    permission: simplesidebar.admin

permissions:
  simplesidebar.use:
    description: Allow sidebar player commands
    default: true
  simplesidebar.admin:
    description: Allow sidebar admin commands
    default: op