name: SimpleSidebar
author: xFlarinFlint
version: 0.8.0_RC1
main: com.gmail.flintintoe.SimpleSidebar

depend: [Vault]
softdepend: [WorldGuard, WorldEdit, PlaceholderAPI]

commands:
  sidebar:
    description: Sidebars player commands
    aliases: [sb]
    usage: /sidebar
    permission: simplesidebar
  adminsidebar:
    description: Sidebars admin commands
    aliases: [asidebar, asb]
    usage: /adminsidebar
    permission: simplesidebaradmin

permissions:
  simplesidebar:
    description: Allows sidebar player commands
    children:
      simplesidebar.use:
        default: true
      simplesidebar.see:
        default: true

  simplesidebaradmin:
    description: Allows sidebar admin commands
    children:
      simplesidebaradmin.check:
        default: op
      simplesidebaradmin.set:
        default: op
      simplesidebaradmin.reload:
        default: op
