#           __ _
#  __   __ / _| | __ _ _ __ ___
#  \ \_/ /| |_| |/ _` | `__/ _ \
#   > _ < |  _| | |_| | |  | __/
#  /_/ \_\|_| |_|\__,_|_|  \___|

# Edit plugin configurations here.

#### Please do not change this value to avoid unexpected errors
config_version: 1.0.0

# Global

#### Enable this plugin
plugin_enabled: true

# Default sidebar

#### If this is true, the first sidebar will be loaded when a player joins the server
first_sidebar_is_default: true

# AFK optimisation (for performance)

#### Duration of inactivity for a player to go into AFK mode
   # Set to 0 to disable AFK optimisation feature
AFK_timer: 30
#### If this is true, the last sidebar will be used when a player enters AFK mode
   # With this enabled, a player cannot set their sidebar to the last sidebar
last_sidebar_is_afk: true

