name: SimpleSidebar
author: Flarin
version: 0.3.0-SNAPSHOT
main: com.gmail.flintintoe.simplesidebar.SimpleSidebar

depend: []
softdepend: [Vault, WorldGaurd]

commands:
  sidebar:
    description: Sidebar player commands
    aliases: [sb]
    usage: /sidebar
    permission: sidebar.use
  sidebaradmin:
    description: Sidebar admin commands
    aliases: [asidebar, asb]
    usage: /adminsidebar
    permission: sidebar.admin

permissions:
  sidebar.use:
    description: Allow sidebar player commands
    default: true
  sidebar.admin:
    description: Allow sidebar admin commands
    default: op